Hira/deep reverse
tasawernawaz/python-test-problems pull request #15
Opened 2022-08-16 13:48 UTC by HiraIjaz

2022-08-23 08:23 UTC, tasawernawaz requested changes

2022-08-23 08:23 UTC, tasawernawaz commented on 20_Deep Reverse.py
> +            value = deep_reverse(i)
what is the purpose of `value`

2022-08-26 16:58 UTC, HiraIjaz commented on 20_Deep Reverse.py
> +            value = deep_reverse(i)
it was there my mistake.

2022-08-29 10:24 UTC, tasawernawaz approved these changes

2022-08-29 14:11 UTC, merged