Add files via upload
tasawernawaz/python-test-problems pull request #5
Opened 2022-08-16 09:01 UTC by HiraIjaz

2022-08-18 14:38 UTC, tasawernawaz commented on 5_IDENTITY matrix Check.py
> +    identityMat = np.eye(size)
rename this to `lower_case`

2022-08-23 09:01 UTC, tasawernawaz requested changes

2022-08-23 09:01 UTC, tasawernawaz commented on 5_IDENTITY matrix Check.py
> +        return False
can we do this `Return np.array_equal(np.array(matrix), identity_mat)`

2022-08-24 11:36 UTC, HiraIjaz commented on 5_IDENTITY matrix Check.py
> +        return False
sure

2022-08-26 16:58 UTC, HiraIjaz commented on 5_IDENTITY matrix Check.py
> +    identityMat = np.eye(size)
done

2022-08-29 10:24 UTC, tasawernawaz approved these changes

2022-08-29 14:12 UTC, merged